version: '3'

services:
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    ports:
    - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data
    networks:
      - app-network

  registry-webserver:
    image: nginx
    container_name: registry-webserver
    restart: unless-stopped
    ports:
      - "580:80"
      - "5443:5443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./mime.types:/etc/nginx/mime.types
      - ssl_certs:/etc/nginx/ssl_certs
      - snippets:/etc/nginx/snippets
      - dhparam:/etc/ssl/certs
    depends_on:
      - registry
    networks:
      - app-network

volumes:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/eaxr/docker-registry/views/
      o: bind
  ssl_certs:
    driver: local
    driver_opts:
      type: none
      device: /home/eaxr/docker-registry/ssl_certs/
      o: bind
  snippets:
    driver: local
    driver_opts:
      type: none
      device: /home/eaxr/docker-registry/snippets/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/eaxr/docker-registry/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
